[tools]
# Programming Languages
python = "3.13.13"
java = ["17", "21"]
go = "latest"
gleam = "latest"
node = "latest"
1password-cli = "2.32.0"

# IaC
terraform = ["1.15.8"]

# Cargo Plugins
"cargo:mergiraf" = "latest"

[settings]
legacy_version_file_disable_tools = ["terraform"]
experimental = true

[tasks.install_tools]
description = "Install tools specified in the configuration file."
run = "pip install headroom-ai[all]"
