[[users]]
name = "yuk1ty"
email = "yuk1ty@users.noreply.github.com"

[[users]]
name = "helloyuki33"
email = "helloyuki33@users.noreply.github.com"

[[users]]
name = "toyoda_sansan"
email = "toyoda_sansan@users.noreply.github.com"
