name: dotfiles try build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: |
          brew uninstall --force $(brew list)
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
