name: dotfiles try build

on:
  push:
    branches: [main]

jobs:
  dotfiles:
    runs-on: macos-14
    timeout-minutes: 180
    env:
      HOMEBREW_BUNDLE_BREW_SKIP: "awscli"

    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: |
          brew upgrade

          # Reset the environment to install brew formulas correctly
          brew uninstall --force $(brew list)

          # Remove symlink to install Python@3.12 correctly
          # rm /usr/local/bin/2to3-3.12
          # rm /usr/local/bin/idle3.12
          # rm /usr/local/bin/pydoc3.12
          # rm /usr/local/bin/python3.12
          # rm /usr/local/bin/python3.12-config

          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
