name: dotfiles try build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Set MacOS.
        run: make
        working-directory: dot_bin
